--PL/SQL Code

--Page 8 Form on VDK_Order

--INSERT_ORDER
DECLARE
    id integer;
BEGIN

SELECT VDK_Customer_customer_id INTO id FROM VDK_Account
WHERE account_id = :P1_USERNAME;
INSERT INTO VDK_ORDER(DATE_ORDERED, SHIP_DATE, VDK_Customer_customer_id)
VALUES (SYSDATE(), :P8_SHIP_DATE, id)
RETURNING ORDER_ID INTO :P8_ORDER_ID;
END;

--INSERT_APPROVE_ORDER
BEGIN
INSERT INTO VDK_APPROVE_ORDER(VDK_employee_employee_id, VDK_Order_Order_id)
VALUES (100, :P8_ORDER_ID);
END;

--INSERT_STATUS
BEGIN
INSERT INTO VDK_STATUS(order_status)
VALUES ('Pending Order')
RETURNING STATUS INTO :P8_VDK_STATUS_STATUS;
END;

--UPDATE_ORDER_STATUS
BEGIN
UPDATE VDK_ORDER SET VDK_STATUS_STATUS = :P8_VDK_STATUS_STATUS
                WHERE ORDER_ID = :P8_ORDER_ID; 
END;


--Page 9 Form on VDK_Customer

--INSERT_CUSTOMER
BEGIN
INSERT INTO VDK_CUSTOMER(NAME, EMAIL_ADDRESS, CREDIT_CARD_NUM, ADDRESS, PHONE_NUMBER)
VALUES (:P9_NAME, :P9_EMAIL_ADDRESS, :P9_CREDIT_CARD_NUM, :P9_ADDRESS, :P9_PHONE_NUMBER)
RETURNING CUSTOMER_ID into :P9_CUSTOMER_ID;
END;

--INSERT_ACCOUNT
BEGIN
INSERT INTO VDK_ACCOUNT(USERNAME, VDK_Employee_employee_id, VDK_Customer_customer_id, TYPE)
VALUES (:P9_USERNAME, NULL, :P9_CUSTOMER_ID, 'Customer')
RETURNING account_id into :P9_VDK_ACCOUNT_ACCOUNT_ID;
END;


--UPDATE_ACCOUNT

UPDATE VDK_CUSTOMER SET VDK_ACCOUNT_ACCOUNT_ID = :P9_VDK_ACCOUNT_ACCOUNT_ID
WHERE CUSTOMER_ID = :P9_CUSTOMER_ID; 


--Page 13 Form on VDK_Shoe

--Insert Shoe

BEGIN
INSERT INTO VDK_SHOE(SIZES, COLOR, STYLE, PRICE, SHOELACE_COLOR)
VALUES (:P13_SIZE, :P13_COLOR, :P13_STYLE, (50 * :P13_QUANTITY), :P13_SHOELACE_COLOR)
RETURNING SHOE_ID into :P13_SHOE_ID;

END;

--INSERT_ORDER_ITEM

BEGIN
INSERT INTO VDK_ORDER_ITEM(QUANTITY, VDK_Order_order_id, VDK_Shoe_shoe_id)
VALUES (:P13_QUANTITY, :P8_ORDER_ID, :P13_SHOE_ID);
END;

--INSERT_SHOE_PATTERN

DECLARE
    pattern_list APEX_APPLICATION_GLOBAL.VC_ARR2;
    curr_pattern_id integer;

BEGIN

IF(:P13_PATTERNS IS NOT NULL) THEN

pattern_list := APEX_UTIL.STRING_TO_TABLE(:P13_PATTERNS);

FOR i IN 1..pattern_list.COUNT LOOP

    SELECT PATTERN_ID INTO curr_pattern_id FROM VDK_Pattern
        WHERE PATTERN_NAME = pattern_list(i);

    INSERT INTO VDK_SHOE_PATTERN
    (VDK_SHOE_SHOE_ID, VDK_PATTERN_PATTERN_ID)
    VALUES 
    (:P13_SHOE_ID, curr_pattern_id);

END LOOP;

END IF;

END;


--INSERT_LOGO

BEGIN
INSERT INTO VDK_LOGO(LOGO_STYLE, VDK_SHOE_SHOE_ID)
VALUES (:P13_LOGO_LOGO_ID, :P13_SHOE_ID)
RETURNING LOGO_ID into :P13_VDK_LOGO_LOGO_ID;
END;

--UPDATE_LOGO_ID

BEGIN
UPDATE VDK_SHOE SET VDK_LOGO_LOGO_ID = :P13_VDK_LOGO_LOGO_ID
                WHERE SHOE_ID = :P13_SHOE_ID; 
END;


--Page 17 Create Logo

--P17_INSERT_LOGO
INSERT INTO VDK_LOGO(LOGO_STYLE)
    VALUES(:P17_LOGO_STYLE);


--Page 21 Form on VDK_Employee

--INSERT_EMPLOYEE
BEGIN
INSERT INTO VDK_EMPLOYEE(NAME, EMAIL_ADDRESS, ADDRESS, PHONE_NUMBER, JOB)
VALUES (:P21_NAME, :P21_EMAIL_ADDRESS, :P21_ADDRESS, :P21_PHONE_NUMBER, :P21_JOB)
RETURNING EMPLOYEE_ID into :P21_EMPLOYEE_ID;
END;


--INSERT_ACCOUNT

BEGIN
INSERT INTO VDK_ACCOUNT(USERNAME, VDK_Employee_employee_id, VDK_Customer_customer_id, TYPE)
VALUES (:P21_USERNAME, :P21_EMPLOYEE_ID, NULL, 'Employee');
END;

--UPDATE_ACCOUNT

UPDATE VDK_EMPLOYEE SET VDK_ACCOUNT_ACCOUNT_ID = :P21_VDK_ACCOUNT_ACCOUNT_ID
WHERE EMPLOYEE_ID = :P21_EMPLOYEE_ID; 

--Page 27 Form on Approving Order

--Update Order Status

DECLARE
    curr_status integer;
BEGIN

SELECT VDK_STATUS_STATUS INTO curr_status FROM VDK_Order
                WHERE ORDER_ID = :P27_ORDER_ID;

UPDATE VDK_STATUS SET ORDER_STATUS = 'Approved',
                DESCRIPTION = :P27_DESCRIPTION
                WHERE status = curr_status; 

END;


--Page 31 Form on VDK_Complaint

--INSERT_COMPLAINT

DECLARE
    curr_customer_id integer;
BEGIN
IF (:P31_COMMENT IS NOT NULL) THEN
SELECT c.CUSTOMER_ID into curr_customer_id from VDK_Customer c
WHERE c.VDK_Account_account_id = :P1_USERNAME;

INSERT INTO VDK_Complaint(COMMENTS, VDK_EMPLOYEE_EMPLOYEE_ID, VDK_Customer_customer_id, VDK_ORDER_ORDER_ID)
    VALUES (:P31_COMMENT, 120, curr_customer_id, :P31_VDK_ORDER_ORDER_ID)
RETURNING complaint_id INTO :P31_COMPLAINT_ID;    
END IF;
END;

--UPDATE_ORDER_COMPLAINT

        UPDATE VDK_ORDER SET VDK_COMPLAINT_COMPLAINT_ID = :P31_COMPLAINT_ID
            WHERE ORDER_ID = :P31_VDK_ORDER_ORDER_ID; 



--Page 34 Send Complaint to Manager

--UPDATE_COMPLAINT

BEGIN
IF (:P34_CHECK = 1) THEN
UPDATE VDK_Complaint SET VDK_EMPLOYEE_EMPLOYEE_ID = 121
WHERE COMPLAINT_ID = :P34_COMPLAINT_ID;
END IF;
END;


--Page 36 Delete Complaint

--UPDATE_ORDER

UPDATE VDK_Order SET VDK_COMPLAINT_COMPLAINT_ID = NULL
WHERE ORDER_ID = :P36_VDK_ORDER_ORDER_ID;

--DELETE_COMPLAINT

BEGIN
IF (:P36_DELETE = 1) THEN

DELETE FROM VDK_Complaint WHERE complaint_id = :P36_COMPLAINT_ID;
END IF;
END;